import type { CountingSystemConfig } from "./types";

/**
 * Seed data for all supported counting systems (SPEC.md §3).
 * Add a new system by adding an entry here — never by branching on
 * system id elsewhere in the app.
 */
export const COUNTING_SYSTEMS: readonly CountingSystemConfig[] = [
  {
    id: "hi-lo",
    name: "Hi-Lo",
    difficulty: "easy",
    balanced: true,
    supportsDeviations: true,
    bettingCorrelation: 0.97,
    insuranceCorrelation: 0.76,
    tagValues: {
      "2": 1,
      "3": 1,
      "4": 1,
      "5": 1,
      "6": 1,
      "7": 0,
      "8": 0,
      "9": 0,
      "10": -1,
      A: -1,
    },
  },
  {
    id: "ko",
    name: "KO (Knock-Out)",
    difficulty: "common",
    balanced: false,
    supportsDeviations: false,
    bettingCorrelation: 0.98,
    insuranceCorrelation: 0.78,
    tagValues: {
      "2": 1,
      "3": 1,
      "4": 1,
      "5": 1,
      "6": 1,
      "7": 1,
      "8": 0,
      "9": 0,
      "10": -1,
      A: -1,
    },
  },
  {
    id: "hi-opt-1",
    name: "Hi-Opt I",
    difficulty: "common",
    balanced: true,
    supportsDeviations: false,
    bettingCorrelation: 0.88,
    insuranceCorrelation: 0.85,
    tagValues: {
      "2": 0,
      "3": 1,
      "4": 1,
      "5": 1,
      "6": 1,
      "7": 0,
      "8": 0,
      "9": 0,
      "10": -1,
      A: 0,
    },
  },
  {
    id: "hi-opt-2",
    name: "Hi-Opt II",
    difficulty: "advanced",
    balanced: true,
    supportsDeviations: false,
    bettingCorrelation: 0.91,
    insuranceCorrelation: 0.91,
    tagValues: {
      "2": 1,
      "3": 1,
      "4": 2,
      "5": 2,
      "6": 1,
      "7": 1,
      "8": 0,
      "9": 0,
      "10": -2,
      A: 0,
    },
  },
  {
    id: "omega-2",
    name: "Omega II",
    difficulty: "advanced",
    balanced: true,
    supportsDeviations: false,
    bettingCorrelation: 0.92,
    insuranceCorrelation: 0.85,
    tagValues: {
      "2": 1,
      "3": 1,
      "4": 2,
      "5": 2,
      "6": 2,
      "7": 1,
      "8": 0,
      "9": -1,
      "10": -2,
      A: 0,
    },
  },
  {
    id: "wong-halves",
    name: "Wong Halves",
    difficulty: "expert",
    balanced: true,
    supportsDeviations: false,
    bettingCorrelation: 0.99,
    insuranceCorrelation: 0.89,
    tagValues: {
      "2": 0.5,
      "3": 1,
      "4": 1,
      "5": 1.5,
      "6": 1,
      "7": 0.5,
      "8": 0,
      "9": -0.5,
      "10": -1,
      A: -1,
    },
  },
  {
    id: "zen",
    name: "Zen Count",
    difficulty: "expert",
    balanced: true,
    supportsDeviations: false,
    bettingCorrelation: 0.96,
    insuranceCorrelation: 0.85,
    tagValues: {
      "2": 1,
      "3": 1,
      "4": 2,
      "5": 2,
      "6": 2,
      "7": 1,
      "8": 0,
      "9": -1,
      "10": -2,
      A: -1,
    },
  },
] as const;
